<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AA-PC" name="framework_testng.Testng_Method_Dependencies" tests="8" failures="1" timestamp="15 May 2019 07:51:31 GMT" time="0.000" errors="1">
  <testcase name="User_login" time="0.000" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="ComposeEmail" time="0.000" classname="framework_testng.Testng_Method_Dependencies">
    <failure type="java.lang.AssertionError" message="expected [msg] but found [emsg]">
      <![CDATA[java.lang.AssertionError: expected [msg] but found [emsg]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at framework_testng.Testng_Method_Dependencies.ComposeEmail(Testng_Method_Dependencies.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- ComposeEmail -->
  <testcase name="Browser_launch" time="0.000" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="Verify_Email_At_Sentemails" time="0.000" classname="framework_testng.Testng_Method_Dependencies">
    <error type="java.lang.Throwable" message="Method Testng_Method_Dependencies.Verify_Email_At_Sentemails()[pri:6, instance:framework_testng.Testng_Method_Dependencies@457e2f02] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Testng_Method_Dependencies.Verify_Email_At_Sentemails()[pri:6, instance:framework_testng.Testng_Method_Dependencies@457e2f02] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- Verify_Email_At_Sentemails -->
  <testcase name="App_Load" time="0.000" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="Search_email" time="0.000" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="Verify_Email_At_inbox" time="0.000" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="User_Signout" time="0.000" classname="framework_testng.Testng_Method_Dependencies"/>
</testsuite> <!-- framework_testng.Testng_Method_Dependencies -->
